name: ecommerce_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^4.2.1
  flutter_native_splash: 2.4.0
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0
  provider: ^6.1.5+1
  intl: ^0.20.2
  google_fonts: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  image_path: "assets/images/app_logo.png"

  android: true
  ios: true

  android_12:
    background_color: "#FFFFFF"
    foreground_image: "assets/images/app_logo.png"

  web:
    generate: true
    image_path: "assets/images/app_logo.png"
    sizes: [192, 512]

flutter:
  uses-material-design: true

  assets:
    - assets/images/

flutter_native_splash:
  # Light Mode (White background, uses your single logo)
  color: "#FFFFFF"
  image: assets/images/app_logo.png

  # Dark Mode (Dark background, uses the same single logo)
  color_dark: "#1A1A1A"
  image_dark: assets/images/app_logo.png

  # Android 12 specific settings
  android_12:
    color: "#FFFFFF"
    image: assets/images/app_logo.png
    color_dark: "#1A1A1A"
    image_dark: assets/images/app_logo.png

  web: true